# Generated by Django 2.0.7 on 2018-07-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('address', models.TextField()),
                ('artist', models.TextField()),
                ('music', models.TextField()),
                ('price', models.TextField()),
                ('organizer', models.TextField()),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
