# Generated by Django 2.0.7 on 2018-07-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='music',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
